<?xml version="1.0"?>
<package format="3">
  <name>aspace_bringup_pkg</name>
  <version>0.1.0</version>
  <description>System-level bringup for the A-space simulation environment.</description>
  <maintainer email="ricardo@example.com">Ricardo</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
