uas_bringup:
  use_sim_time: true
  group:
    num_uas: 1
    start_id: 1
    namespace_prefix: ua_
  flight_zone_assignment:
    required: true
    default_zone_id: test
  px4:
    directory: /home/rinese/PX4-Autopilot
    binary: build/px4_sitl_default/bin/px4
    sys_autostart: 4001
    sim_model: gz_x500
    standalone_gazebo: true
    instance_offset: -1
    start_delay_s: 1.0
    stagger_s: 0.35
  spawn:
    origin:
    - 3.0
    - 3.0
    - 0.0
    spacing:
    - 3.0
    - 3.0
    - 0.0
    row_length: 5
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  micro_ros_agent:
    start: true
    transport: udp4
    port: 8888
  gazebo_bridge:
    start: true
    node_name: gz_parameter_bridge
    config_file: ''
  drone_odom_broadcaster:
    enabled: true
    start_delay_s: 3.0
    stagger_s: 0.1
    vehicle_odometry_topic: fmu/out/vehicle_odometry
    odom_topic: odom
    reset_service: reset_odom_srv
    odom_frame: odom
    base_frame: base_link
  robot_state_publisher:
    enabled: true
    urdf_file: ''
    publish_frequency: 30.0
