updated_flow_server_node:
  ros__parameters:
    manual_adjustment_trajectories_topic: /manual_adjustment_trajectories
    solved_collision_trajectories_topic: /solved_collision_trajectories

    collision_static_trajectories_topic: /collision_static_trajectories
    available_static_trajectories_topic: /available_static_trajectories

    removed_trajectories_topic: /removed_trajectories
    updated_flow_status_topic: /updated_flow_status

    publish_period_ms: 1000
    log_state_transitions: true
